exports.lyrics = [
`oh, you touch my tralala,`,
`mmm... my ding ding dong.`,
`la la la la la la la,`,
`la la la la la la,`,
`la la la la la la la.`,
`Oh, you touch my tralala`,
`la la la la la la la,`,
`la la la la la la.`,
`mmm... my ding ding dong.`,
`la la la la la la la,`,
`la la la la la la.`,
`Deep in the night,`,
`i'm looking for some fun,`,
`deep in the night,`,
`i'm looking for some love.`,
`de-de-de-deep in the night,`,
`i'm looking for some fun,`,
`deep in the night,`,
`i'm looking for some (ping)`,
`You tease me,`,
`oh please me,`,
`i want you to be my lovetoy,`,
`come near me, don't fear me,`,
`i just can't get enough of you boy.`,
`Oh, you touch my tralala.`,
`la la la.`,
`mmm, my ding ding dong,`,
`oh you touch my tralala,`,
`mmm, my ding ding dong.`,
`la la la...`,
`Deep in the night,`,
`i'm looking for some fun,`,
`deep in the night,`,
`i'm looking for some love.`,
`you tease…`]