exports.lyrics = [
    `Creeper, oh man`,
    `So we back in the mine, got our pick axe swinging side to side, day and night`,
    `This task a grueling one, hope to find some diamonds tonight, oh how they shine`,
    `Then it's heads up, hear a sound you freeze up, turn around and look up, total shock fills your body,`,
    `Is this the end?`,
    `Can't believe it's you again`,
    `I could never forget those eyes`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again, again, again`,
    `'Cause baby tonight, you grab your pick, shovel and bolt again, again, again`,
    `And run, run, run until it's done, done, then you run, run, run until the sun `,
    `Sun comes up in the morn'`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again, again, again`,
    `Just when you think you're safe, hear some hissing from right behind, escape denied`,
    `That's a nice life you have, shame it's gotta end at this time, now you're mine`,
    `Then he blows up, and your health bar it drops, you could use a 1-up, get inside don't be tardy,`,
    `Now you're stuck in there, all alone in despair, half a heart is left now but don't die`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again, again, again`,
    `'Cause baby tonight, you grab your pick, shovel and bolt again, again, again`,
    `And run, run, run until it's done, done, then you run, run, run until the sun `,
    `Sun comes up in the morn'`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again, again, again`,
    `Dig up diamonds, and craft those diamonds`,
    `Looks like that armor's been exercising`,
    `MLG Pro, that diamond sword`,
    `Come at me bro, I got it forged`,
    `Training under the torch light glow`,
    `Hone that form now you're in the zone`,
    `Creepers out prowling, ready for the big fight`,
    `Show them what it feels like`,
    `Come on. Lets go!`,
    `'Cause I'm a warrior baby through and through`,
    `Take my revenge.`,
    `That's what I will do`,
    `Bring it`,
    `You gotta fight baby tonight`,
    `The creeper's trying to steal your stuff again`,
    `It's time to grab your sword, armor and go`,
    `It's time to go get your revenge`,
    `And you fight, fight like it's your last night, then you fight, fight like it's for your life`,
    `Time to show them your bite`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again, again, again`,
    `'Cause baby tonight, the creeper's trying to steal your stuff again`,
    `Swing your sword up high`,
    `'Cause baby tonight, you grab your pick, shovel and bolt again`,
    `Swing your sword down low`,
    `It's time to go`,
    `It's time to go`,
    `It's time to go get your revenge`
]